name: ecommerce
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  flutter_localizations:
    sdk: flutter
    version: ^0.0.0
  intl: ^0.18.1
  go_router: ^13.2.1
  crypto: ^3.0.3
  firebase_core: ^2.28.0
  firebase_auth: ^4.5.0
  flutter_facebook_auth: ^6.2.0
  google_sign_in: ^6.2.1
  google_sign_in_web: ^0.12.4
  provider: ^6.1.2
  flutter_cart: ^0.0.9
  cloud_firestore: ^4.17.5


dev_dependencies:
  animated_text_kit: ^4.2.2
  flutter_svg: ^2.0.10+1
  http: ^1.2.1
  getwidget: ^4.0.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
http:^1:
  2:
    1:
flutter:
  generate: true
  uses-material-design: true

