// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDimAJFxz9IDWQsC2OuQW29fDjbg6ro5IE',
    appId: '1:444382273485:web:2cfa519a091afe027d2e84',
    messagingSenderId: '444382273485',
    projectId: 'ecommerce-176bc',
    authDomain: 'ecommerce-176bc.firebaseapp.com',
    databaseURL: 'https://ecommerce-176bc-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ecommerce-176bc.appspot.com',
    measurementId: 'G-C1VT5RWRGT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPDMKXltzI0xSJd4KzFQuFQoHCpsRDx7g',
    appId: '1:444382273485:android:a45135cda24ab6b27d2e84',
    messagingSenderId: '444382273485',
    projectId: 'ecommerce-176bc',
    databaseURL: 'https://ecommerce-176bc-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ecommerce-176bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZW2U9SM_s1ipoihccvwnC5t3Pz88rw7s',
    appId: '1:444382273485:ios:d01537283911437e7d2e84',
    messagingSenderId: '444382273485',
    projectId: 'ecommerce-176bc',
    databaseURL: 'https://ecommerce-176bc-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ecommerce-176bc.appspot.com',
    iosClientId: '444382273485-9sqhufhs1dbong95k21r0ig6u6sbterd.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZW2U9SM_s1ipoihccvwnC5t3Pz88rw7s',
    appId: '1:444382273485:ios:40aba1e32827e9237d2e84',
    messagingSenderId: '444382273485',
    projectId: 'ecommerce-176bc',
    databaseURL: 'https://ecommerce-176bc-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ecommerce-176bc.appspot.com',
    iosClientId: '444382273485-ulu5gmi2u9cdurnt7o8asi74olu3mrj8.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce.RunnerTests',
  );
}
